index.html: *.md
	pandoc index.md -w html -s  -c practico.css -o index.html
	pandoc vi.md -w html -s  -c practico.css -o vi.html
scp:
	scp *.css *.html russell:public_html/prog20/
scppdf:
	scp *.pdf russell:public_html/prog20/
practicos:
#	pandoc 01linuxvic.md -o 01linuxvic.html -s --self-contained  -c practico.css --toc
#	pandoc 02.md -o 02.html -s --self-contained  -c practico.css --toc
#	pandoc 03.md -o 03.html -s --self-contained  -c practico.css --toc
#	pandoc 04.md -o 04.html -s --self-contained  -c practico.css --toc
#	pandoc 05.md -o 05.html -s --self-contained  -c practico.css --toc
#	pandoc 06.md -o 06.html -s --self-contained  -c practico.css --toc
#	pandoc 07.md -o 07.html -s --self-contained  -c practico.css --toc
#	pandoc 08.md -o 08.html -s --self-contained  -c practico.css --toc
# 25 de mayo feriado
#	pandoc 09.md -o 09.html -s --self-contained -c practico.css --toc
#	pandoc 10.md -o 10.html -s --self-contained -c practico.css --toc
# 15/6 feriado
# parcial 2 puntos tareas - 4 puntos arreglos - 4 puntos funciones
#	pandoc final_julio2020a.md -o fj2020.html -s --self-contained  -c practico.css --toc
	pandoc final_octubre2020a.md -o fo2020.html -s --self-contained  -c practico.css --toc

